name: costa_toolbox
description: "A comprehensive toolkit for Costa Coffee field service engineers."
publish_to: 'none'
version: 1.0.1+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.10+1
  flutter_riverpod: ^2.6.1
  riverpod_annotation: ^2.3.5
  url_launcher: ^6.2.5
  pdfx: ^2.6.0  # Replaced flutter_pdfview with pdfx
  path_provider: ^2.1.2
  shared_preferences: ^2.5.2
  crypto: ^3.0.6
  firebase_core: ^3.12.1
  firebase_auth: ^5.5.1
  cloud_firestore: ^5.6.5
  firebase_storage: ^12.4.4
  firebase_analytics: ^11.4.4
  go_router: ^14.8.1
  archive: ^4.0.5
  file_picker: ^10.1.2
  permission_handler: ^12.0.0+1
  flutter_file_dialog: ^3.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  mockito: ^5.4.4
  build_runner: ^2.4.8
  riverpod_generator: ^2.4.0
  riverpod_lint: ^2.3.7
  custom_lint: ^0.6.4

flutter:
  uses-material-design: true
  
  assets:
    # Data files
    - assets/filter_list.json
    - assets/cpd.json
    - assets/finest_filter_capacities.json
    - assets/fresh_filter_capacities.json
    - assets/standard_filter_capacities.json
    - assets/documents.json
    - assets/sample.pdf

    # Documents
    - assets/documents/schaerer_scb_parts.pdf
    - assets/documents/soul_s10_installation_manual.pdf
    - assets/documents/soul_s10_spare_parts.pdf
    
    # Images
    - assets/images/c50.png
    - assets/images/c300.png
    - assets/images/c500.png
    - assets/images/c1100.png
    - assets/images/svcpd.png
    - assets/images/MK2.png
    - assets/images/MK3.png
    - assets/images/MK4.png
    - assets/images/SOULS10.png
    - assets/images/MARLOW.png
    - assets/images/MARLOW12.png
    - assets/images/brewer.png
    - assets/images/boiler.png
    - assets/images/grinder.png
    
    # Backgrounds
    - assets/background/bluewave.png
    
    # Icons
    - assets/icons/cup.svg
    - assets/icons/trans_cclogo.png

  fonts:
    - family: CostaDisplayO
      fonts:
        - asset: assets/fonts/CostaDisplayO-Bold.ttf
          weight: 700
        - asset: assets/fonts/CostaDisplayO-Light.ttf
          weight: 300
        - asset: assets/fonts/CostaDisplayO-Regular.ttf
          weight: 400
        
    - family: CostaDisplayWaveO
      fonts:
        - asset: assets/fonts/CostaDisplayWaveO-Bold.ttf
          weight: 700
        - asset: assets/fonts/CostaDisplayWaveO-Light.ttf
          weight: 300
        - asset: assets/fonts/CostaDisplayWaveO-Regular.ttf
          weight: 400
        
    - family: CostaTextO
      fonts:
        - asset: assets/fonts/CostaTextO-Bold.ttf
          weight: 700
        - asset: assets/fonts/CostaTextO-Light.ttf
          weight: 300
        - asset: assets/fonts/CostaTextO-Regular.ttf
          weight: 400